[package]
name = "gem-board"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
init_with = "1.1.0"
petgraph = "0.6.4"