[package]
name = "gem-board"
version = "0.1.1"
edition = "2021"

[workspace]
members = [
    ".",
    "lib",
]

[dependencies]
# Local
gem-board-lib = { path = "lib" }
# Remote
rand = "0.8.5"
init_with = "1.1.0"